# Generated by Django 6.0.3 on 2026-03-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_news_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='main_video_url',
            field=models.TextField(verbose_name='Главное видео (base64)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(blank=True, null=True, verbose_name='Превью (base64)'),
        ),
    ]
