# Generated by Django 6.0.3 on 2026-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_video_main_video_url_alter_video_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurement',
            old_name='contract_number',
            new_name='contractNumber',
        ),
    ]
