# Generated by Django 6.0.3 on 2026-03-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_contract_number_procurement_contractnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Сумма'),
        ),
    ]
