# Generated by Django 6.0.3 on 2026-03-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_procurement_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurement',
            name='method',
            field=models.CharField(choices=[('direct', 'Прямой'), ('tender', 'Через тендер')], default='direct', max_length=20, verbose_name='Способ закупки'),
        ),
    ]
