# Generated by Django 6.0.3 on 2026-03-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_procurement_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='method',
            field=models.CharField(choices=[('direct', 'Прямое заключение договора'), ('quotation', 'Запрос котировок'), ('simple', 'Простейшая закупка'), ('tender', 'Конкурс')], default='direct', max_length=20, verbose_name='Способ закупки'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='type',
            field=models.CharField(choices=[('goods', 'Товар'), ('services', 'Услуга'), ('works', 'Работа')], default='goods', max_length=20, verbose_name='Тип'),
        ),
    ]
