# Generated by Django 6.0.3 on 2026-04-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_procurement_method_alter_procurement_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vacancy',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
