# Generated by Django 6.0.3 on 2026-04-16 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_vacancy_remove_photo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер закупки'),
        ),
    ]
