# Generated by Django 6.0.3 on 2026-04-17 10:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_news_id_alter_photo_id_alter_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Legislation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('file_url', models.TextField(verbose_name='Файл (base64)')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Законодательство',
                'verbose_name_plural': 'Законодательство КР',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalAct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Название документа')),
                ('file_url', models.TextField(verbose_name='Файл (base64)')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер файла (байт)')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Локальный акт',
                'verbose_name_plural': 'Локальные акты',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
