# Generated by Django 6.0.3 on 2026-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_legislation_localact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.AddField(
            model_name='news',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (Кыргызча)'),
        ),
        migrations.AddField(
            model_name='news',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Описание (Русский)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (Кыргызча)'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default=1, max_length=255, verbose_name='Название (Русский)'),
            preserve_default=False,
        ),
    ]
