# Generated by Django 5.0.8 on 2026-04-27 04:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_news_description_remove_news_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО заявителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('complaint_type', models.CharField(choices=[('rights_violation', 'Нарушение прав'), ('technical_error', 'Техническая ошибка'), ('employee_complaint', 'Жалоба на сотрудника'), ('service_quality', 'Качество услуг'), ('waste_issue', 'Проблема с вывозом отходов'), ('other', 'Другое')], max_length=50, verbose_name='Тип обращения')),
                ('subject', models.CharField(max_length=500, verbose_name='Тема обращения')),
                ('description', models.TextField(verbose_name='Суть жалобы')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='Дата происшествия')),
                ('incident_location', models.CharField(blank=True, max_length=500, verbose_name='Место происшествия')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения (base64)')),
                ('consent', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('status', models.CharField(choices=[('new', 'Новое'), ('in_progress', 'В обработке'), ('reviewed', 'Рассмотрено'), ('resolved', 'Решено'), ('rejected', 'Отклонено')], default='new', max_length=50, verbose_name='Статус')),
                ('admin_response', models.TextField(blank=True, verbose_name='Ответ администратора')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
            },
        ),
    ]
