# Generated by Django 5.0.8 on 2026-04-27 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
